### ISSUE TITLE
protobuf能否升级到2.5.x版本

### ISSUE THREAD

**Issue by lqzhang** [aliyun/aliyun-odps-java-sdk#2]
flume protobuf最新版本是2.5.x，现在版本2.4 存在​兼容问题 ，可以升级到2.5.x版本吗

**Comment by lyman** [comment]
着急的话可以先改改我们的开源代码自己编译一个用

**Comment by lyman** [comment]
从 0.31.6-public 起，开始发布 shaded 包，这个版本的 pb 是 relocation 过的，不会和用户代码的 pb 冲突了

https://repo1.maven.org/maven2/com/aliyun/odps/odps-sdk-core/0.31.6-public/

```
        <dependency>
            <groupId>com.aliyun.odps</groupId>
            <artifactId>odps-sdk-core</artifactId>
            <version>0.31.6-public</version>
            <classifier>shaded</classifier>
        </dependency>
```
