### ISSUE TITLE
odps数据迁移至ADS

### ISSUE THREAD

**Issue by JoshuaYin** [aliyun/aliyun-odps-java-sdk#23]
你好，我在使用阿里云的odps，现在需要将odps的数据迁移至阿里云的ADS，但是不知道odps的sdk上能否操作？怎么操作？ 或者说Task包下的哪个类可以执行odps控制台上的预设迁移脚本？

**Comment by lyman** [comment]
『预设迁移脚本』是指 DataWorks 的同步任务？这个是不是 odps sdk cover 的范围，需要联系 DataWorks 询问是否有 sdk 可用。

https://help.aliyun.com/document_detail/125178.html
