### ISSUE TITLE
下载SQLTask报错：java.io.IOException: Premature EOF

### ISSUE THREAD

**Issue by Malaban** [aliyun/aliyun-odps-java-sdk#25]
有时候正常，有时候报错。
content: java.io.IOException: Premature EOF
--
+9 | [2020-04-13 04:40:33]10.200.9.151content: at sun.net.www.http.ChunkedInputStream.fastRead(ChunkedInputStream.java:257)
+10 | [2020-04-13 04:40:33]10.200.9.151content: at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:689)
+11 | [2020-04-13 04:40:33]10.200.9.151content: at java.io.FilterInputStream.read(FilterInputStream.java:133)
+12 | [2020-04-13 04:40:33]10.200.9.151content: at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3444)
+13 | [2020-04-13 04:40:33]10.200.9.151content: at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
+14 | [2020-04-13 04:40:33]10.200.9.151content: at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
+15 | [2020-04-13 04:40:33]10.200.9.151content: at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
+16 | [2020-04-13 04:40:33]10.200.9.151content: at com.google.protobuf.CodedInputStream$StreamDecoder.readRawBytesSlowPathOneChunk(CodedInputStream.java:2967)
+17 | [2020-04-13 04:40:33]10.200.9.151content: at com.google.protobuf.CodedInputStream$StreamDecoder.readRawBytesSlowPath(CodedInputStream.java:2887)
+18 | [2020-04-13 04:40:33]10.200.9.151content: at com.google.protobuf.CodedInputStream$StreamDecoder.readRawBytes(CodedInputStream.java:2877)
+19 | [2020-04-13 04:40:33]10.200.9.151content: at com.aliyun.odps.tunnel.io.ProtobufRecordStreamReader.read(ProtobufRecordStreamReader.java:166)
+20 | [2020-04-13 04:40:33]10.200.9.151content: at com.aliyun.odps.tunnel.io.TunnelRecordReader.read(TunnelRecordReader.java:34)
+21 | [2020-04-13 04:40:33]10.200.9.151content: at com.aliyun.odps.tunnel.io.ProtobufRecordStreamReader.read(ProtobufRecordStreamReader.java:203)
+22 | [2020-04-13 04:40:33]10.200.9.151content: at com.aliyun.odps.tunnel.io.TunnelRecordReader.read(TunnelRecordReader.java:34)
+23 | [2020-04-13 04:40:33]10.200.9.151content: at com.rada.bigdata.query.utils.Tunnel.tunnel(Tunnel.java:96)
+24 | [2020-04-13 04:40:33]10.200.9.151content: at com.rada.bigdata.query.utils.Tunnel.runTunnel(Tunnel.java:74)
+25 | [2020-04-13 04:40:33]10.200.9.151content: at com.rada.bigdata.query.job.AnyscTask.updateBatchIdMapping(AnyscTask.java:36)
+26 | [2020-04-13 04:40:33]10.200.9.151content: at com.rada.bigdata.query.job.AnyscTask$$FastClassBySpringCGLIB$$be8ffcb1.invoke(<generated>)
+27 | [2020-04-13 04:40:33]10.200.9.151content: at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
+28 | [2020-04-13 04:40:33]10.200.9.151content: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
+29 | [2020-04-13 04:40:33]10.200.9.151content: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

**Comment by lyman** [comment]
消费的太慢了。每个 reader 背后是一个 http 连接，这个 http 连接空闲超过一定时间（不会超过 300s）会被服务端主动关闭，关闭了之后就有可能是 premature eof。

一个办法是自己本地做一定数量 record 的缓存。

**Comment by Malaban** [comment]
好的，谢谢




在2020年04月22日 00:38，Li Ruibo<notifications@github.com> 写道：

消费的太慢了。每个 reader 背后是一个 http 连接，这个 http 连接空闲超过一定时间（不会超过 300s）会被服务端主动关闭，关闭了之后就有可能是 premature eof。

一个办法是自己本地做一定数量 record 的缓存。
