### ISSUE TITLE
tag missing problem

### ISSUE THREAD

**Issue by CChengjie** [aliyun/aliyun-odps-java-sdk#50]
I'm doing a research on tags .
We found that versions like **0.34.6** was released in Maven, but there was no corresponding tag in github, Can you help me with this?
1）What is the reason for tag's absence of 0.34.6?( i find the commit message of v0.34.5 is "**Update version to 0.34.6-public**"; and exist "**Update version to 0.34.5-public**" before)

- a、This version code has problems, such as the loophole, compatibility and interface issues, etc.
- b、This version has functional problems, such as unreasonable function planning, basic function cannot be used
- c、Forgot to tag
- d、Don't care or is too trouble
- e、Don't care or is too trouble
- f、others，_

2） To solve this problem, we propose a method that can find the true commit of version to help developers quickly locate the problem code and fix the bug. Here are the possible true commits given by our method. Can you confirm whether or not the actual commits are included, and if not, which ones?
**0.34.5**
['ccc36ffa2f152bafadce3aeeb0747f1a841ecde8']
**0.34.6**
['5e8c40020dedffe1432c4639d578eb076fe79de2']

♥ This question is very important to our research. Thank you for your time!

**Comment by dingxin-tech** [comment]
hi～ @CChengjie， 
     Thank you for your patience. We're currently reviewing open issues and noticed this has been inactive for some time. Have you managed to resolve this issue, or is it still something that needs attention?
     If you think this issue can be closed, please let us know. If we do not hear from you within two weeks, we will assume the issue has been resolved and will close it. Of course, you are always welcome to reopen it if needed.
     Thank you for your understanding.
