### ISSUE TITLE
dependency jackson-mapper-asl:1.9.x security issue

### ISSUE THREAD

**Issue by CoolHsu** [aliyun/aliyun-odps-java-sdk#52]
请问有计划在新版本fix org.codehaus.jackson:jackson-mapper-asl:1.9.x security issue吗？谢谢

**Comment by Just-CJ** [comment]
+1

**Comment by dingxin-tech** [comment]
目前我们没有计划在新版本中修复 org.codehaus.jackson:jackson-mapper-asl:1.9.x 的安全问题。经过测试，升级到这个库的新版本存在兼容性问题。不便之处，敬请谅解。谢谢理解。
