### ISSUE TITLE
请问读分区表的时候启动很慢 上百个将近一分钟 可能是什么原因

### ISSUE THREAD

**Issue by nocmk2** [aliyun/aliyun-odps-java-sdk#53]
请问读分区表的时候启动很慢 上百个将近一分钟 可能是什么原因

**Comment by yefanjiang** [comment]
启动慢指的是什么？是哪个部分的启动慢？如果是job启动慢，可能的原因是在排队。请提供更多信息～
此外，如果可以，请提供相关的代码和运行时信息。

**Comment by dingxin-tech** [comment]
hi～ @nocmk2， 感谢你的耐心等待。
我们目前正在审核所有的未解决问题，注意到这个问题已经有一段时间没有活跃了。你是否已经解决了这个问题，还是仍然需要关注？
如果你认为这个问题可以关闭，请告诉我们。如果两周内我们没有收到你的回复，我们将假设问题已经解决，并将关闭此问题。当然，如果需要，你可以随时重新打开它。

谢谢！
