### ISSUE TITLE
创建外部表

### ISSUE THREAD

**Issue by qingbozhang** [aliyun/aliyun-odps-java-sdk#55]
外部表使用PARQUET格式 SQL里这样指定 stored as PARQUET
但是在SDK里只能传 storedBy，会被解析为 STORED BY

**Comment by dingxin-tech** [comment]
hi～ @qingbozhang， 感谢你的耐心等待。
我们目前正在审核所有的未解决问题，注意到这个问题已经有一段时间没有活跃了。你是否已经解决了这个问题，还是仍然需要关注？
如果你认为这个问题可以关闭，请告诉我们。如果两周内我们没有收到你的回复，我们将假设问题已经解决，并将关闭此问题。当然，如果需要，你可以随时重新打开它。

谢谢！
