### ISSUE TITLE
请问有方法通过odps的sdk来获取到表间的血缘关系吗？

### ISSUE THREAD

**Issue by Usigned** [aliyun/aliyun-odps-java-sdk#63]
请问有方法通过odps的sdk来获取到表间的血缘关系吗？
之前看到一个blog是通过内置表分析来获取的，请问有没有开发的api？
https://developer.aliyun.com/article/738779?spm=a2c6h.13066369.question.7.17bd2ee9KSp18y

**Comment by zdx19981006** [comment]
目前SDK还没有这个接口，我们后面会新增一个Task类型来支持

**Comment by dingxin-tech** [comment]
由于没有进一步的更新，我们将关闭此问题。如果你发现问题仍然存在或有任何进一步的问题，请随时重新打开此问题或创建新的问题。
感谢你的理解和合作。
