### ISSUE TITLE
有没有OSS外表自定义解析器是解析excel的例子

### ISSUE THREAD

**Issue by jqdelove** [aliyun/aliyun-odps-java-sdk#69]
有需求需要用excel文件作为oss外表的文件源，想征求一个excel解析器的例子

**Comment by dingxin-tech** [comment]
目前没有现成的 execl 解析器的用例，但是可以参考以下文档和代码，实现你自己的解析器来创建外表。

[示例：读取OSS文本数据（自定义解析器）](https://help.aliyun.com/zh/maxcompute/user-guide/read-oss-data?spm=a2c4g.11186623.0.0.2cd57367j3zNw0)

[示例：通过自定义解析器创建OSS外部表](https://help.aliyun.com/zh/maxcompute/user-guide/create-an-oss-external-table?spm=a2c4g.11186623.0.0.5c2962aeHUF5xL#section-rat-30e-5e8)

[csv 文件解析器相关代码](https://github.com/aliyun/aliyun-odps-java-sdk/tree/release/0.48.x/odps-sdk-impl/odps-udf-example/src/main/java/com/aliyun/odps/udf/example/text)

**Comment by jqdelove** [comment]
您好，我已收到您的消息，我会尽快给您回复。

**Comment by dingxin-tech** [comment]
目前我们没有计划在新版本中修复 org.codehaus.jackson:jackson-mapper-asl:1.9.x 的安全问题。经过测试，升级到这个库的新版本存在兼容性问题。不便之处，敬请谅解。谢谢理解。

**Comment by jqdelove** [comment]
好的，感谢，麻烦您看下我新提的PR，之前提供的例子不支持多字符的列分隔符，我稍微修改了一下
