### ISSUE TITLE
odps读oss数据数据为空

### ISSUE THREAD

**Issue by onine007** [aliyun/aliyun-odps-java-sdk#7]
使用这个文件夹下面的代码打成jar包,aliyun-odps-java-sdk/odps-sdk-impl/odps-udf-example/src/main/java/com/aliyun/odps/udf/example/text/
使用gzip压缩,可以写到oss上,但是读取的时候有问题,
1. TextExtractor代码里没有gzip解压缩 (我在moveToNextStream方法是加上了)
2. 我在读较多列的时候后面的列会变成null,而单独select那个列的时候,就没有问题

**Comment by onine007** [comment]
1. 描述反了, 实际是在outputer的时候没有gzip压缩

**Comment by dingxin-tech** [comment]
hi～ @online007， 感谢你的耐心等待。
我们目前正在审核所有的未解决问题，注意到这个问题已经有一段时间没有活跃了。你是否已经解决了这个问题，还是仍然需要关注？
如果你认为这个问题可以关闭，请告诉我们。如果两周内我们没有收到你的回复，我们将假设问题已经解决，并将关闭此问题。当然，如果需要，你可以随时重新打开它。

谢谢！
