### ISSUE TITLE
odps 使用 Tunnel 下载大数据量的表

### ISSUE THREAD

**Issue by YanZhuangz** [aliyun/aliyun-odps-java-sdk#74]
### 背景

使用 SDK 下载数据量达 8E 的数据

### 实现方案

1. 使用`InstanceTunnel`来创建`DownloadSession`
2. `openRecordReader`获取读取的`TunnelRecordReader`
3. 执行迭代循环或者`#read()` 方法获取数据记录

### 问题描述

在按照当前做法时，在循环迭代读取时，耗时比较久

### 期望

1. 在大数据量的下载背景下，有没有什么方案可以推荐
2. 参考了 aliyun-odps-console 的实现，会采用多个`openRecordReader`的方式来下载数据，但是仍没有避免`#read()` 耗时的问题，有没有什么方式可以替代`#read`方法

### 其他

1. 我们在数据上传下载处理上，上传的速度比下载的速度明显的快很多，想了解下这两块的区别

**Comment by dingxin-tech** [comment]
您好，目前没有方式能够替代`#read`方法。在我们的测试中，`#read`方法的耗时是较小的，能否给出具体的案例看下是否`#read`方法耗时成为瓶颈？

如您所说，在大数据量的下载背景下，您可以使用多个 openRecordReader 来下载数据，通过提高并发量来加速数据下载

目前在上传链路，我们引入了缓冲区来避免与服务端的长链接，能够一定程度上的加块上传速度。而在下载链路，目前仍然通过长链接的方式进行下载

**Comment by YanZhuangz** [comment]
感谢支持！

目前我们重新分析了一下，有两点操作导致的性能问题：

1. 使用的 endpoint 是公网域名，在带宽上有一定的上限
2. 我们在批次处理上使用了`openRecordReader` 来打开一定量的批次，每次批处理都重新打开，导致频繁创建链接，不同环境耗时会不同。

我们针对第二点在做调整，减少`openRecordReader`的操作。
